controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login_check:
    path: /api/login_check
sign_up:
    path: /sign-up
    controller: App\Controller\SignUpController
    methods: ['POST']